import * as anchor from '@coral-xyz/anchor';
import { Program } from '@coral-xyz/anchor';
import * as fs from 'fs';
import * as path from 'path';

/**
 * AgentMemory Deployment Script
 * 
 * This script deploys the AgentMemory program and sets up the frontend configuration.
 * 
 * Usage:
 *   npx ts-node deploy.ts
 * 
 * Prerequisites:
 *   - Solana CLI configured for devnet
 *   - Anchor installed
 *   - Devnet SOL in wallet
 */

async function main() {
  console.log('🚀 AgentMemory Deployment\n');

  // Configure provider
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  console.log('📋 Configuration:');
  console.log(`  RPC: ${provider.connection.rpcEndpoint}`);
  console.log(`  Wallet: ${provider.wallet.publicKey.toString()}`);

  // Check wallet balance
  const balance = await provider.connection.getBalance(provider.wallet.publicKey);
  console.log(`  Balance: ${balance / 1e9} SOL`);

  if (balance < 0.5 * 1e9) {
    console.warn('\n⚠️  Warning: Low balance. Run: solana airdrop 2');
  }

  // Load program
  console.log('\n📦 Loading program...');
  
  // Get program ID from keypair
  const keypairPath = path.join(__dirname, '../target/deploy/agent_memory-keypair.json');
  
  if (!fs.existsSync(keypairPath)) {
    console.error('❌ Program keypair not found. Run deploy.sh first or generate keypair:');
    console.error('   solana-keygen new --outfile target/deploy/agent_memory-keypair.json');
    process.exit(1);
  }

  const programId = anchor.web3.Keypair.fromSecretKey(
    new Uint8Array(JSON.parse(fs.readFileSync(keypairPath, 'utf-8')))
  ).publicKey;

  console.log(`  Program ID: ${programId.toString()}`);

  // Verify program is deployed
  console.log('\n🔍 Checking deployment...');
  const accountInfo = await provider.connection.getAccountInfo(programId);
  
  if (!accountInfo) {
    console.error('❌ Program not found on chain. Deploy first:');
    console.error('   anchor deploy --provider.cluster devnet');
    process.exit(1);
  }

  if (!accountInfo.executable) {
    console.error('❌ Account exists but is not executable');
    process.exit(1);
  }

  console.log('  ✓ Program deployed and executable');
  console.log(`  Data size: ${accountInfo.data.length} bytes`);

  // Save configuration
  console.log('\n💾 Saving configuration...');
  
  const envPath = path.join(__dirname, '../../app/.env.local');
  const envContent = `# AgentMemory Configuration
# Generated by deploy.ts on ${new Date().toISOString()}
NEXT_PUBLIC_AGENT_MEMORY_PROGRAM_ID=${programId.toString()}
NEXT_PUBLIC_SOLANA_RPC_URL=${provider.connection.rpcEndpoint}
NEXT_PUBLIC_NETWORK=devnet
`;

  fs.writeFileSync(envPath, envContent);
  console.log(`  ✓ Configuration saved to: ${envPath}`);

  // Print summary
  console.log('\n✅ Deployment Summary:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`Program ID:   ${programId.toString()}`);
  console.log(`Network:      Devnet`);
  console.log(`RPC URL:      ${provider.connection.rpcEndpoint}`);
  console.log(`Wallet:       ${provider.wallet.publicKey.toString()}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  
  console.log('\n🔗 Explorer Links:');
  console.log(`  Program:    https://explorer.solana.com/address/${programId.toString()}?cluster=devnet`);
  console.log(`  Wallet:     https://explorer.solana.com/address/${provider.wallet.publicKey.toString()}?cluster=devnet`);
  
  console.log('\n📖 Next Steps:');
  console.log('  1. cd ../../app');
  console.log('  2. npm install');
  console.log('  3. npm run dev');
  console.log('  4. Open http://localhost:3000');
}

main().catch((error) => {
  console.error('\n❌ Deployment failed:');
  console.error(error);
  process.exit(1);
});
